# Generated by Django 3.1.3 on 2020-11-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonuserfieldmixin',
            name='id_no',
            field=models.IntegerField(default=0),
        ),
    ]
