# Generated by Django 3.1.3 on 2020-11-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_auto_20201120_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='updated',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
