# Generated by Django 3.1.3 on 2020-11-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_auto_20201116_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='cv',
            new_name='id_img',
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='remarks',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='job_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bank_accountno',
            field=models.IntegerField(default=0),
        ),
    ]
