# Generated by Django 3.1.3 on 2020-11-18 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_commonuserfieldsmixins'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonUserFieldsMixins',
        ),
    ]
