# Generated by Django 3.1.3 on 2020-11-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_auto_20201120_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='updated',
        ),
    ]
