# Generated by Django 3.1.3 on 2020-11-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_delete_commonuserfieldsmixins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
