# Generated by Django 3.1.3 on 2020-11-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0004_remove_policy_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
