# Generated by Django 3.1.3 on 2020-11-24 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0005_policy_updated'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='policy',
            index_together={('id',)},
        ),
        migrations.RemoveField(
            model_name='policy',
            name='slug',
        ),
    ]
