# Generated by Django 3.1.3 on 2020-11-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0006_auto_20201124_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
