# Generated by Django 3.1.3 on 2020-11-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0007_auto_20201124_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='signed',
            field=models.DateField(auto_now_add=True),
        ),
    ]
